### ISSUE TITLE
Intermittent issue: alignX: "undefined" kills app in version 9.0.0-alpha.15

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#990]
As a developer, I know intermittent, non-consistent issues that can be solved by a refresh are of the worst kind to troubleshoot.  I'm seeing this issue with version 9.0.0-alpha.15 of the @stripe/ui-extension-sdk about 80% of the time.  

I  see this error in version 9  (an error I don't see in version 8):

![image](https://github.com/user-attachments/assets/0f516dbf-21a6-4d38-a7de-0236261a2473)

![image](https://github.com/user-attachments/assets/fe260af7-3ad2-4ded-9854-c5c67aebfd37)

I don't have any empty <Box> elements or instances of any attribute of `alignX: undefined`.  I'm posting this as a placeholder to add a ticket to this issue, as I understand I'm working with a beta version...so I don't expect a response to this.  The frustrating thing about this bug is that it is intermittent. A browser refresh will solve the issue in 20% of refresh cases.  I'm still trying to isolate the problem in my code that creates this issue...so this might be a "my" issue report. But I'm posting this to see if there is an easily solvable resolution to this bug.  I'm happy to share my source code privately with any interested party.

I understand I'm working with a beta version, and this issue can be solved by simply using version 8.  But I'm just flagging this as an issue in the beta version.

**Comment by matebek-stripe** [comment]
Hi @bensontrent, thank you for reporting this issue. The behavior you're experiencing is indeed unexpected. As mentioned in our [SDK upgrade guide](https://docs.stripe.com/stripe-apps/upgrade-stripes-ui-extension-sdk#what%E2%80%99s-new-in-v9), we have been enforcing property validation during development since v9 of `@stripe/ui-extension-sdk`. 

To better understand and address your issue, it would be helpful if you could provide a code example that reproduces the problem in isolation. When an invalid prop is encountered, you should see the source of the issue, as shown in the following screenshot:

![image](https://github.com/user-attachments/assets/e90b9f1a-b2db-49eb-b0cd-4d68e404d56f)

However, the error you're seeing appears to be different from what we typically expect from our SDK's property validation. We need to investigate further to understand how this is occurring in your case.

**Comment by bensontrent** [comment]
Based on your feedback on how the error _should_ appear, I haven't confirmed this, but it seems to be an issue when using `<> <SomeOtherComponent /></>` empty _container_ elements in React. I'll do some more tests to confirm.

**Comment by bensontrent** [comment]
@matebek-stripe  I've given you private access to the Parcelcraft app at https://github.com/parcelcraft/parcelcraft-app

This is also exhibiting a new intermittent error on our Main Dashboard view:

![image](https://github.com/user-attachments/assets/fe69b966-ec50-4d17-b4b2-6991814f00d1)

I've confirmed this bug appears in version 9.0.0-alpha.15.  The issue does not appear in 8.9.1.  I'm no closer to identifying the issue, but it appears to be an issue with the app loader itself, (I've added an ErrorBoundry to my code to catch errors).

**Comment by aaronhernandez-stripe** [comment]
Hello @bensontrent I took a look at the code you shared and it looks good, I tried to reproduce the issue In the Stripe dashboard using your app but I was unable to see the same issue you are experiencing.
The only thing that stood out is that you are installing react@^18.3.1 while the only version of react we currently support is react@17.0.2 (https://docs.stripe.com/stripe-apps/how-ui-extensions-work#apps-cant-control-the-react-version), while I don't think this would cause the error I recommend to downgrade to that version and see if the error is still present.

Could you share more details about your test setup so I can try to mimic it as close as possible:
- Are you seeing this error only when developing, on a published app or both?
- What browser and version are you using?
- What version of the stripe apps cli are you using `stripe apps -v`?
- are you using yarn or npm to install dependencies?

Any other information that could help us reproduce/debug the issue is welcome, Thanks!

**Comment by bensontrent** [comment]
Hi @aaronhernandez-stripe! 

**Are you seeing this error only when developing, on a published app or both?**

- Only in development:
- Our published app presents no errors (published with @stripe/ui-extension-sdk  8.9.1)
- When previewing with  @stripe/ui-extension-sdk  9.0.0-alpha.15, we see the errors.
- This normally wouldn't be an issue, we'd use version 8.9.1 and be happy.  However, we are developing an Embedded App Viewport, which requires the beta version.

**What browser and version are you using?**

- Chrome Version 130

**What version of the stripe apps cli are you using stripe apps -v?**

- I updated the CLI and the apps CLI plugin (no change in the issue)

![image](https://github.com/user-attachments/assets/896c0d0a-9d75-48ef-820b-bd8f169c5d59)


**are you using yarn or npm to install dependencies?**

- npm


More tips to reproduce the error:

- For simplicity, you can install the external test link for com.productivity.parcelcraft (Privately request a link from me if needed)
- Ensure you have added your EasyPost API key in the Parcelcraft Settings  (you can privately request a special production key for testing from benson@parcelcraft.com)
- Add your origin address in the Parcelcraft settings.
- Browse to the app view and change your view settings to view **all payments** or **all invoices** (assuming your test account has test payments or invoices to view), or browse to a PaymentDetailView or InvoiceDetailView
- If the errors fail to trigger, please request a meeting with me at https://calendly.com/parcelcraft/meeting

**Comment by bensontrent** [comment]
@matebek-stripe  I see you've scheduled a meeting with me for tomorrow. I'll see you there.

New findings:

- Downgrading to version 9.0.0-alpha.14 fixes this error; downgrading unblocks my roadblock.
- The ErrorBoundary in version 9.0.0-alpha.15 appears to be over-eager compared to alpha-14.

**Comment by matebek-stripe** [comment]
@bensontrent We have just deployed a fix, could you please test it on your end to see if the error is indeed resolved?

**Comment by bensontrent** [comment]
@matebek-stripe The settings view is indeed fixed.  I still have an issue with the main dashboard view:

![image](https://github.com/user-attachments/assets/9a4dc938-8300-492d-b0d9-8cb800755848)

![image](https://github.com/user-attachments/assets/efc8f4eb-78e4-4357-bd99-03defe6a66a5)

**Comment by matebek-stripe** [comment]
A change has been rolled out to fix all the reported errors. Closing this issue now. Thank you @bensontrent for bringing this to our attention!
